version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - grafana.env
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - influxdb_nk  

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - influxdb.env
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    networks:
      - influxdb_nk  

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  influxdb_nk:  
    external: true  
