services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - grafana.env
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: